// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OTPMailer is an autogenerated mock type for the OTPMailer type
type OTPMailer struct {
	mock.Mock
}

// SendOTP provides a mock function with given fields: otpCode, receiver
func (_m *OTPMailer) SendOTP(otpCode string, receiver string) error {
	ret := _m.Called(otpCode, receiver)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(otpCode, receiver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOTPMailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewOTPMailer creates a new instance of OTPMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOTPMailer(t mockConstructorTestingTNewOTPMailer) *OTPMailer {
	mock := &OTPMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
