// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// OTPMailer is an autogenerated mock type for the OTPMailer type
type OTPMailer struct {
	mock.Mock
}

// SendOTP provides a mock function with given fields: ctx, otpCode, receiver
func (_m *OTPMailer) SendOTP(ctx context.Context, otpCode string, receiver string) error {
	ret := _m.Called(ctx, otpCode, receiver)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, otpCode, receiver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendPasswordReset provides a mock function with given fields: ctx, token, receiver
func (_m *OTPMailer) SendPasswordReset(ctx context.Context, token string, receiver string) error {
	ret := _m.Called(ctx, token, receiver)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, receiver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOTPMailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewOTPMailer creates a new instance of OTPMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOTPMailer(t mockConstructorTestingTNewOTPMailer) *OTPMailer {
	mock := &OTPMailer{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
