// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/snykk/go-rest-boilerplate/internal/business/entities"
	usersrepo "github.com/snykk/go-rest-boilerplate/internal/datasources/repositories/users"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// ChangeActiveUser provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) ChangeActiveUser(ctx context.Context, inDom *entities.UserDomain) error {
	ret := _m.Called(ctx, inDom)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserDomain) error); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) GetByEmail(ctx context.Context, inDom *entities.UserDomain) (entities.UserDomain, error) {
	ret := _m.Called(ctx, inDom)

	var r0 entities.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserDomain) entities.UserDomain); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(entities.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.UserDomain) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) Store(ctx context.Context, inDom *entities.UserDomain) (entities.UserDomain, error) {
	ret := _m.Called(ctx, inDom)

	var r0 entities.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserDomain) entities.UserDomain); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(entities.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.UserDomain) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id string) (entities.UserDomain, error) {
	ret := _m.Called(ctx, id)

	var r0 entities.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.UserDomain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, offset, limit
func (_m *UserRepository) List(ctx context.Context, filter usersrepo.ListFilter, offset int, limit int) ([]entities.UserDomain, error) {
	ret := _m.Called(ctx, filter, offset, limit)

	var r0 []entities.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, usersrepo.ListFilter, int, int) []entities.UserDomain); ok {
		r0 = rf(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.UserDomain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usersrepo.ListFilter, int, int) error); ok {
		r1 = rf(ctx, filter, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *UserRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
