### GET A ROOT ENDPOINT
GET http://localhost:8080/api/

### REGISTRATION FOR NEW USER
POST http://localhost:8080/api/v1/auth/regis
Content-Type: application/json

{
  "username": "najibfikri",
  "email": "najibfikri26@gmail.com",
  "password":"123123sdf!"
}

### SEND OTP 
POST http://localhost:8080/api/v1/auth/send-otp
Content-Type: application/json

{
  "email": "najibfikri26@gmail.com"
}


### VERIF OTP 
POST http://localhost:8080/api/v1/auth/verif-otp
Content-Type: application/json

{
  "email": "najibfikri26@gmail.com",
  "code":"102429"
}


### LOGIN 
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "najibfikri26@gmail.com",
  "password":"123123sdf!"
}