// Package main is the API entry point.
//
// @title           Go REST Boilerplate API
// @version         1.0
// @description     A starting point for building RESTful APIs in Go using the Gin framework, sqlx for PostgreSQL, and Redis for caching. Implementation follows Clean Architecture principles as described by Uncle Bob.
// @termsOfService  https://github.com/snykk/go-rest-boilerplate
//
// @contact.name   Najib Fikri
// @contact.url    mailto:najibfikri26@gmail.com
//
// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT
//
// @host      localhost:8080
// @BasePath  /api/v1
// @schemes   http https
//
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Bearer access token issued by /auth/login or /auth/refresh.
package main

import (
	"runtime"

	"github.com/snykk/go-rest-boilerplate/cmd/api/server"
	_ "github.com/snykk/go-rest-boilerplate/docs" // OpenAPI spec, generated by `make swag`
	"github.com/snykk/go-rest-boilerplate/internal/config"
	"github.com/snykk/go-rest-boilerplate/internal/constants"
	"github.com/snykk/go-rest-boilerplate/pkg/logger"
)

func init() {
	if err := config.InitializeAppConfig(); err != nil {
		logger.Fatal(err.Error(), logger.Fields{constants.LoggerCategory: constants.LoggerCategoryConfig})
	}
	// Re-init logger with env-derived settings (production = JSON;
	// dev = console). The package-level init() already provided a
	// sensible default so the line above can log even if this fails.
	_ = logger.InitDefault(loggerConfig(), logger.InstanceZap)
	logger.Info("configuration loaded", logger.Fields{constants.LoggerCategory: constants.LoggerCategoryConfig})
}

func loggerConfig() logger.Config {
	cfg := logger.Config{
		Level:         logger.LevelInfo,
		EnableConsole: true,
		AppName:       "go-rest-boilerplate",
	}
	if config.AppConfig.Environment == constants.EnvironmentProduction {
		cfg.ConsoleJSONFormat = true
	} else if config.AppConfig.Debug {
		cfg.Level = logger.LevelDebug
	}
	return cfg
}

func main() {
	numCPU := runtime.NumCPU()
	logger.WithFields(logger.Fields{constants.LoggerCategory: constants.LoggerCategoryConfig}).
		Infof("The project is running on %d CPU(s)", numCPU)

	if runtime.NumCPU() > 2 {
		runtime.GOMAXPROCS(numCPU / 2)
	}

	app, err := server.NewApp()
	if err != nil {
		logger.Panic(err.Error(), logger.Fields{constants.LoggerCategory: constants.LoggerCategoryServer})
	}
	if err := app.Run(); err != nil {
		logger.Fatal(err.Error(), logger.Fields{constants.LoggerCategory: constants.LoggerCategoryServer})
	}
}
